#!/bin/sh
# kpm_verify.sh — Ed25519 signature verification for KPM modules.
#
# This file is intended to be sourced from service.sh (and any other
# caller that wants to verify a .kpm before loading it). It exposes
# one public function:
#
#   verify_kpm_sig <kpm_file> <sig_file>
#
# Behavior:
#   * Returns 0 (success) when the signature is valid.
#   * Returns 1 (failure) when verification fails for any reason
#     (missing sig file, bad sig format, signature mismatch, openssl
#     not present, etc.). The caller SHOULD log and skip loading the
#     module in that case.
#
# .kpm.sig file format (MVP):
#   The first non-empty line of the file is the 64-byte Ed25519
#   signature encoded as 128 lowercase hex characters, with no
#   whitespace. Any other lines are ignored. This keeps the file
#   grep-friendly and trivially parseable on Android shell.
#
# Public key:
#   KPM_SIGN_PUBKEY_HEX is a hardcoded 32-byte Ed25519 public key
#   encoded as 64 lowercase hex characters.
#   The current value is a DEV/TEST key. TODO(security): replace with
#   a release key managed out-of-band, and consider loading the key
#   from /data/adb/patchnest/kpm_sign_pubkey instead of hardcoding it.
#
# Tooling:
#   We use `openssl dgst -ed25519 -verify` (OpenSSL >= 1.1.1). This is
#   available in modern Android (toybox/busybox builds frequently ship
#   it; on stock AOSP it is in /system/bin/openssl). No Android
#   SDK/NDK dependency is introduced.
#
#   We intentionally avoid the BSD `signify` and any prebuilt NDK
#   crypto blob. If openssl is missing, verify_kpm_sig returns 1 and
#   the caller treats that as a verification failure (which is the
#   safe default when enforcement is on).
#
# Backward compatibility:
#   * When REQUIRE_KPM_SIGNATURES=0 (or unset), service.sh will NOT
#     call this function at all.
#   * When enforcement IS on, the caller passes the .kpm path and the
#     expected .sig path. If the sig file does not exist, this
#     function returns 1 and the caller skips the load.

# ---------- bundled public key ----------
# Generated locally for the v0.3.0 ultracode audit (2026-06-06).
# Replaces the previous RFC 8032 Test 1 key, which was the well-known
# "everyone has the private key" value — meaning anyone could forge
# a .kpm.sig that this verifier would accept.
#
# This key is the corresponding PUBLIC half of an Ed25519 pair
# generated by the maintainer on 2026-06-06. The matching private
# key is held out-of-band (NOT in this repo); use it via
#     openssl pkeyutl -sign -inkey <priv> -rawin -in <kpm> \
#                     -out <kpm>.sig
# to produce .kpm.sig files for distribution.
#
# The test vector in kpm_verify__require_openssl() below uses this
# same public key with a probe input ("probe") so that openssl
# compatibility is checked against the actual deployment key.
KPM_SIGN_PUBKEY_HEX="a6cee3371d164daf9ad2ed38ecaf1d492e7867fc6df31f810e69eaa0dd45259b"

# ---------- internal helpers ----------

# kpm_verify__log <msg>
# Append a timestamped line to the service log when one is writable.
# Service.sh sets $PNDIR and $LOG; we tolerate their absence so that
# this script is safe to source from any context.
kpm_verify__log() {
    if [ -n "$LOG" ] && [ -n "$PNDIR" ] && [ -d "$PNDIR" ]; then
        printf '[%s] kpm_verify: %s\n' "$(date)" "$1" >> "$LOG" 2>/dev/null
    fi
}

# kpm_verify__hex_to_bin <hex_string> <out_file>
# Write the binary representation of <hex_string> to <out_file>.
# Returns 0 on success, 1 if the input is not valid hex of even length.
# This is intentionally written in pure POSIX shell (no awk ord(),
# no xxd, no perl) so it works on stock Android mksh/toybox/ash.
kpm_verify__hex_to_bin() {
    local _hex=$1
    local _out=$2
    local _i _fmt _expected_sz _actual_sz
    # Reject any non-hex char early.
    case "$_hex" in
        *[!0-9a-fA-F]*) return 1 ;;
    esac
    if [ $(( ${#_hex} % 2 )) -ne 0 ]; then
        return 1
    fi
    # printf "%b" on mksh interprets \xHH correctly. We build the
    # argument by joining "\xHH" sequences; printf then emits the raw
    # bytes in one shot. This avoids spawning a process per byte.
    _i=1
    _fmt=""
    while [ $_i -le ${#_hex} ]; do
        _fmt="${_fmt}\\x$(printf '%s' "$_hex" | cut -c${_i}-$((_i+1)))"
        _i=$((_i + 2))
    done
    if ! printf '%b' "$_fmt" > "$_out" 2>/dev/null; then
        rm -f "$_out" 2>/dev/null
        return 1
    fi
    # Verify output size matches expected binary length.
    _expected_sz=$(( ${#_hex} / 2 ))
    _actual_sz=$(wc -c < "$_out" 2>/dev/null)
    if [ "$_actual_sz" != "$_expected_sz" ]; then
        rm -f "$_out" 2>/dev/null
        return 1
    fi
    return 0
}

# kpm_verify__require_openssl
# Returns 0 if `openssl dgst -ed25519 -verify` is usable, 1 otherwise.
#
# We probe by running a self-signed Ed25519 test vector with the
# *deployment* public key. If openssl on the device supports Ed25519,
# the verify call returns 0; if not, the call fails with
# "digital envelope routine:unsupported" or similar. Using the
# deployment key (not a well-known test vector) ensures the probe
# really exercises the same key path that production verification
# will use, and not some quirk that just happens to accept the
# RFC 8032 Test 1 vector.
#
# Test vector: (priv=<maintainer priv, not shipped>,
#               pub=a6cee3371d164daf9ad2ed38ecaf1d492e7867fc6df31f810e69eaa0dd45259b,
#               msg="probe" (5 bytes),
#               sig=886199b494a8dcb9ddec3a48385f4ea7e3cbefcc90198c6c807fd2434125b20e32f1b8cdd817e782f7fcf80860c4a32f7c49006089a4efefb4b734bbcb30f703).
# The probe writes a 5-byte file ("probe") into /data/local/tmp; we
# avoid mktemp to keep the script portable to minimal Android shells
# without /system/bin/mktemp.
kpm_verify__require_openssl() {
    local _probekey _probesig _probeinput _probekeyfile _probesigfile
    if ! command -v openssl >/dev/null 2>&1; then
        return 1
    fi
    _probekey="a6cee3371d164daf9ad2ed38ecaf1d492e7867fc6df31f810e69eaa0dd45259b"
    _probesig="886199b494a8dcb9ddec3a48385f4ea7e3cbefcc90198c6c807fd2434125b20e32f1b8cdd817e782f7fcf80860c4a32f7c49006089a4efefb4b734bbcb30f703"
    _probeinput=/data/local/tmp/.kpm_probe_input_$$.bin
    _probekeyfile=/data/local/tmp/.kpm_probekey_$$.bin
    _probesigfile=/data/local/tmp/.kpm_probesig_$$.bin
    if ! printf '%s' "probe" > "$_probeinput" 2>/dev/null; then
        return 1
    fi
    if ! kpm_verify__hex_to_bin "$_probekey" "$_probekeyfile"; then
        rm -f "$_probeinput" 2>/dev/null
        return 1
    fi
    if ! kpm_verify__hex_to_bin "$_probesig" "$_probesigfile"; then
        rm -f "$_probeinput" "$_probekeyfile" 2>/dev/null
        return 1
    fi
    if openssl dgst -ed25519 -verify "$_probekeyfile" \
            -signature "$_probesigfile" "$_probeinput" \
            >/dev/null 2>&1; then
        rm -f "$_probeinput" "$_probekeyfile" "$_probesigfile" 2>/dev/null
        return 0
    fi
    rm -f "$_probeinput" "$_probekeyfile" "$_probesigfile" 2>/dev/null
    return 1
}

# ---------- public API ----------

# verify_kpm_sig <kpm_file> <sig_file>
# Returns 0 if the signature is valid, 1 otherwise.
verify_kpm_sig() {
    local _kpm=$1
    local _sig=$2
    local _sig_hex _tmpdir _pub_bin _sig_bin _ok

    if [ -z "$_kpm" ] || [ -z "$_sig" ]; then
        kpm_verify__log "missing arguments"
        return 1
    fi
    if [ ! -f "$_kpm" ]; then
        kpm_verify__log "kpm file not found: $_kpm"
        return 1
    fi
    if [ ! -f "$_sig" ]; then
        kpm_verify__log "sig file not found: $_sig"
        return 1
    fi

    if ! kpm_verify__require_openssl; then
        kpm_verify__log "openssl with ed25519 not available; failing closed"
        return 1
    fi

    # Read the hex signature (first non-empty line) and validate.
    _sig_hex=$(awk 'NF{print; exit}' "$_sig" 2>/dev/null | tr -d ' \t\r\n')
    case ${#_sig_hex} in
        128) ;;
        *)
            kpm_verify__log "sig file is not 64 bytes (got ${#_sig_hex} hex chars)"
            return 1 ;;
    esac
    case "$_sig_hex" in
        *[!0-9a-fA-F]*)
            kpm_verify__log "sig file contains non-hex characters"
            return 1
            ;;
    esac

    # Decode the public key and signature into temp files. We use
    # /data/local/tmp (world-writable on debug builds, but the files
    # are short-lived and contain no secrets — just a public key and
    # a signature). If that fails, fall back to /tmp.
    _tmpdir=""
    if command -v mktemp >/dev/null 2>&1; then
        _tmpdir=$(mktemp -d /data/local/tmp/kpm_verify.XXXXXX 2>/dev/null) || \
            _tmpdir=$(mktemp -d /tmp/kpm_verify.XXXXXX 2>/dev/null)
    fi
    if [ -z "$_tmpdir" ] || [ ! -d "$_tmpdir" ]; then
        _tmpdir=/data/local/tmp/kpm_verify.$$
        mkdir -p "$_tmpdir" 2>/dev/null
    fi
    # Defend against symlink attack: reject if _tmpdir is a symlink.
    if [ -L "$_tmpdir" ]; then
        kpm_verify__log "temp dir is a symlink; possible attack"
        return 1
    fi
    if [ ! -d "$_tmpdir" ]; then
        kpm_verify__log "could not create temp dir"
        return 1
    fi
    trap 'rm -rf "$_tmpdir" 2>/dev/null' EXIT INT TERM HUP
    _pub_bin="$_tmpdir/pub.bin"
    _sig_bin="$_tmpdir/sig.bin"

    if ! kpm_verify__hex_to_bin "$KPM_SIGN_PUBKEY_HEX" "$_pub_bin"; then
        kpm_verify__log "bundled public key is not valid hex"
        rm -rf "$_tmpdir" 2>/dev/null
        return 1
    fi
    if ! kpm_verify__hex_to_bin "$_sig_hex" "$_sig_bin"; then
        kpm_verify__log "sig hex decode failed"
        rm -rf "$_tmpdir" 2>/dev/null
        return 1
    fi

    # Run the actual verification. openssl returns 0 on success, 1 on
    # signature mismatch, and non-zero (often 1) on malformed input.
    _ok=1
    if openssl dgst -ed25519 -verify "$_pub_bin" \
            -signature "$_sig_bin" "$_kpm" >/dev/null 2>&1; then
        _ok=0
    fi

    rm -rf "$_tmpdir" 2>/dev/null
    trap - EXIT INT TERM HUP

    if [ "$_ok" -eq 0 ]; then
        kpm_verify__log "signature OK: $(basename "$_kpm")"
        return 0
    fi
    kpm_verify__log "signature INVALID: $(basename "$_kpm")"
    return 1
}
